# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """$username$hostname: $directory$fill$all"""

command_timeout = 2400

[fill]
symbol = "."
style = "subtext0"

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold #a6e3a1)"
error_symbol = "[✗](bold #f38ba8) "

[username]
format = '[$user](bold #b4befe)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[$ssh_symbol](bold #b4befe)[@](bold #cdd6f4)[$hostname](bold #b4befe)"
trim_at = ".zalando.net"
disabled = false

[directory]
truncation_length = 0
truncation_symbol = "…/"
read_only = " "
truncate_to_repo = false
read_only_style = "#eba0ac"
style = "#89b4fa"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[aws]
symbol = "  "
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[c]
symbol = " "
format = '\[[$symbol($version(-$name))]($style)\]'

[cmake]
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
style = "bold #94e2d5"
format = '([\[⏱ $duration\]]($style))'

[docker_context]
symbol = " "
format = '\[[$symbol$context]($style)\]'

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
style = "bold #cba6f7"
symbol = " "
format = '([\[$symbol$branch\]]($style))'

[git_metrics]
disabled = false
deleted_style = "bold #fab387"
added_style = "bold #a6e3a1"
format = '[\[+$added]($added_style)/[-$deleted\]]($deleted_style)'

[git_status]
style = "bold #f5c2e7"
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[java]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[kotlin]
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
symbol = " "
format = '\[$symbol[$ram( | $swap)]($style)\]'

[nodejs]
disabled = true
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[package]
style = "bold #89dceb"
symbol = " "
format = '([\[$symbol$version\]]($style))'

[python]
symbol = " "
style = "bold #f9e2af"
format = '([\[$symbol$pyenv_prefix$version(\($virtualenv\))\]]($style))'

[sudo]
format = '\[[as $symbol]\]'

[vagrant]
format = '\[[$symbol($version)]($style)\]'

