# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """$username$hostname: $directory$fill$all"""

command_timeout = 2400

[fill]
symbol = "."
style = "#928374"

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold #689d6a)"
error_symbol = "[✗](bold #cc241d)"

[username]
format = '[$user](bold #ebdbb2)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[$ssh_symbol](bold #d65d0e)[@](bold #a89984)[$hostname](bold #ebdbb2)"
trim_at = ".zalando.net"
disabled = false

[directory]
truncation_length = 0
truncation_symbol = "…/"
read_only = " "
truncate_to_repo = false
read_only_style = "#fb4934"
style = "#d79921"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[aws]
symbol = "󰸏  "
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[c]
symbol = " "
format = '\[[$symbol($version(-$name))]($style)\]'

[cmake]
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
style = "bold #98971a"
format = '([\[󱑆 $duration\]]($style))'

[docker_context]
symbol = " "
format = '\[[$symbol$context]($style)\]'

[gcloud]
symbol = "󱇶 "
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
#style = "bold #cba6f7"
symbol = " "
format = '([\[$symbol$branch\]]($style))'

[git_metrics]
disabled = false
#deleted_style = "bold #fab387"
#added_style = "bold #a6e3a1"
format = '[\[+$added]($added_style)/[-$deleted\]]($deleted_style)'

[git_status]
#style = "bold #f5c2e7"
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[java]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[kotlin]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
symbol = "󱃾 "
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
symbol = " "
format = '\[$symbol[$ram( | $swap)]($style)\]'

[nodejs]
disabled = true
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[package]
#style = "bold #89dceb"
symbol = " "
format = '([\[$symbol$version\]]($style))'

[python]
symbol = " "
#style = "bold #f9e2af"
format = '([\[$symbol$pyenv_prefix$version(\($virtualenv\))\]]($style))'

[sudo]
format = '\[[as $symbol]\]'

[vagrant]
format = '\[[$symbol($version)]($style)\]'

